# Pandas

Pandas is an open source library that provides easy to use data structures and data analysis tools to be used within Python. It is the basis of many other libraries used, mainly for data manipulation purposes.


- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

- It has functions for analyzing, cleaning, exploring, and manipulating data.

- Pandas allows us to analyze big data and make conclusions based on statistical theories.

- Pandas can clean messy data sets, and make them readable and relevant.

- Relevant data is very important in data science.

We will start with the main data structure that is offered within `pandas` library.

## Data Frame

DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.

It can be considered as a relational table (with multiple *indexed* rows and/or *labeled* columns), or dictionary where each value is a list.

### Note:

There is another trivial data structure `series` available in `pandas` library, however it is basically a single column of `DataFrame` and therefore, we focus here mainly on `DataFrame` which is a collection of `series`. This way, we will implicitly cover most of functionality available in `series`.

## Creating DataFrame

In order to create a data from, following things are typically needed:

1. Data in n-dimensional array format.
2. Optional column title/header.
3. Optional index titles.
4. Optional data type (only one data type is allowed, or it can infer from the data).

A constructor is defined for such purpose.

Lets look at our first example.

But before the example, we need to import the `pandas` library. (similar to `numpy` library).

In [1]:
import pandas as pd

In [3]:
df=btch_1={'Name':["Taha","Junaid","Aslam","Areeba","Owais"],
        'Salary':[12000,56000,90000,67000,34500],
        'Age':[23,34,34,23,23],
        'Gender':['Male','Male','Male','Female','Male']

      }

pd.DataFrame(df)

     Name  Salary  Age  Gender
0    Taha   12000   23    Male
1  Junaid   56000   34    Male
2   Aslam   90000   34    Male
3  Areeba   67000   23  Female
4   Owais   34500   23    Male

In [4]:
import pandas as pd
df=btch_2={'Name':['Asif','Aslam','Taha',"ilyas"],
                'Salary':[30000,45000,56000,46000],
                'Age':[35,45,40,34]}

df=pd.DataFrame(btch_2)
display(df)

    Name  Salary  Age
0   Asif   30000   35
1  Aslam   45000   45
2   Taha   56000   40
3  ilyas   46000   34

In [5]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
import pandas as pd

### Create DF with Given n-D Array

Data:    
$\begin{bmatrix}
a11 & a12\\
a21 & a22
\end{bmatrix}
$   
col_names: ['col 1', 'col 2']  
row_index: ['row 1', 'row 2']

In [ ]:
import pandas as pd
dff=pd.DataFrame([['Orange','900'],['Apple','1000']],columns=['Qty ','Price'],index=['Taha','Aslam'])
display(dff)

In [ ]:
import pandas as pd

df = pd.DataFrame([['a11', 'a12'], ['a21', 'a22']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

display(df)

You can also use `print` function, however, `display` does a more aesthetic version of `print`.

In [ ]:
print(df)

Lets create a data frame using a random n-D array.

### Create DF with Random n-D Array

Data: random 3 columns 1000 rows numbers between 0 and 1.     
col_names: ['col 1', 'col 2', 'col 3']

In [ ]:
import numpy as np  # import numpy to use rand function.

df = pd.DataFrame(np.random.rand(1000, 3), columns=['col 1', 'col 2', 'col 3'])

display(df)

### Create DF with Dictionary

Data: three patients data of calories and duration since last checkup.

In [ ]:
#create dictionary

data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}

print(type(data))

In [ ]:
#load data into a DataFrame object:
df = pd.DataFrame(data)

display(df)

However, mostly we read data from file.

### Create DF from CSV (Comma separated Value) File

Lets us read our first file in this course. It is named `Basic-1.csv`.

We will use automatic indexing for rows, for column headers, we will use the first row.

The method is:

    read_csv(filepath, delimiter=',', header=`infer`, names=nodefault, index_col=None).
    
There are many more parameters, but for now we will stick to these.
- filepath is the name of the file along with the path where the file is stored (can be absolute or relative path).
- delimiter (or sep) is the character that indicates that it is the new value, comma is the default separator.
- header indicates if the data contains name of the columns, you can give it an `integer` that is the index of the row that contains header, `None` to indicate that there is no header to the data or let the code `infer` from the data.
- names, its a list of column headers, if you want to provide the headers of the columns on your own. (should be equal to the number of columns).
- index_col is `None` if you want automatic indexing of the row, otherwise, you can indicate which column contains indices for the row. Can be name of the column or the position.

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
#1. Display the above data.
import pandas as pd

df = pd.read_excel('/sample_data_1.xlsx') #, delimiter=',')

# display data
display(df)

    Employee ID                 Name   Salary   Age   Gender  Joining Date
0        6750.0      Henry Alexander  50217.0  33.0     Male    2014-01-13
1        3109.0     Cassandra Wilson  31278.0  45.0   Female    2018-03-21
2        4024.0      Raymond Griffin  44921.0  53.0     Male    2020-12-05
3        1638.0     Stephanie Benson  60234.0  29.0   Female    2019-07-15
4        9536.0   Josephine Hamilton  52918.0  37.0   Female    2012-11-27
..          ...                  ...      ...   ...      ...           ...
69       1802.0         Karen Parker  38210.0  33.0   Female    2011-01-22
70       9641.0          Steven Ward  35123.0  50.0     Male    2018-09-11
71       4930.0           Amy Torres  41132.0  35.0   Female    2016-06-30
72       7261.0         Bobby Howard  39012.0  52.0     Male    2013-12-05
73       8563.0         Judith White  46123.0  41.0   Female    2021-07-18

[74 rows x 6 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee ID    71 non-null     float64
 1    Name          70 non-null     object
 2    Salary        71 non-null     float64
 3    Age           71 non-null     float64
 4    Gender        70 non-null     object
 5    Joining Date  74 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 3.6+ KB

For larger data, it will only display few rows.
You may be interested in viewing the initial rows, or the last ones or randomly.
 - head(n=5), displays the starting rows (default is 5).
 - tail(n=5), displays the ending rows (default is 5).
 - sample(n=1), displays random rows (can also be set to fraction of data, using keyword `frac`), has other parameters as well.

In [15]:
df.head(15)

    Employee ID                 Name   Salary   Age   Gender  Joining Date
0        6750.0      Henry Alexander  50217.0  33.0     Male    2014-01-13
1        3109.0     Cassandra Wilson  31278.0  45.0   Female    2018-03-21
2        4024.0      Raymond Griffin  44921.0  53.0     Male    2020-12-05
3        1638.0     Stephanie Benson  60234.0  29.0   Female    2019-07-15
4        9536.0   Josephine Hamilton  52918.0  37.0   Female    2012-11-27
5        7468.0         James Murphy  19382.0  41.0     Male    2013-10-03
6        5086.0         Robert Hayes  41023.0  57.0     Male    2010-06-21
7        2665.0        John Martinez  48293.0  26.0     Male    2016-05-14
8        3887.0           Lisa Davis      NaN  35.0      NaN    2021-11-17
9        6902.0          Karen Moore  23812.0  40.0   Female    2015-04-22
10       7445.0      Benjamin Wright  45912.0  32.0     Male    2017-08-19
11          NaN                  NaN  38920.0  50.0      NaN    2011-02-24
12       6284.0       Kimberly Clark  51137.0  39.0   Female    2020-09-11
13       3754.0          Laura Scott  21789.0   NaN   Female    2019-05-08
14       9327.0       Edward Johnson  48173.0  34.0     Male    2013-12-01

In [16]:
df.tail(15)

    Employee ID                Name   Salary   Age   Gender  Joining Date
59       8476.0   Christina Russell  45012.0  38.0   Female    2013-01-10
60       5829.0       Matthew Perry  47231.0  55.0     Male    2018-04-26
61       2713.0       Ann Alexander  30123.0  34.0   Female    2020-10-13
62       7941.0      Bryan Martinez  38921.0  43.0     Male    2014-05-03
63       6123.0      Jessica Carter  42124.0  31.0   Female    2016-12-20
64       7698.0      George Stewart  40023.0  48.0     Male    2017-11-07
65       3954.0     Kathryn Roberts  45120.0  37.0   Female    2010-07-29
66       8142.0       Joshua Murphy  47232.0  46.0     Male    2019-03-28
67       2103.0     Nicole Peterson  32912.0  40.0   Female    2015-02-18
68       5374.0      Daniel Bennett  39213.0  54.0     Male    2020-08-16
69       1802.0        Karen Parker  38210.0  33.0   Female    2011-01-22
70       9641.0         Steven Ward  35123.0  50.0     Male    2018-09-11
71       4930.0          Amy Torres  41132.0  35.0   Female    2016-06-30
72       7261.0        Bobby Howard  39012.0  52.0     Male    2013-12-05
73       8563.0        Judith White  46123.0  41.0   Female    2021-07-18

In [ ]:
# prompt: sample uses

df.sample(5) # displays 5 random rows
df.sample(frac=0.1) # displays 10% of the rows randomly.

In [17]:
df.sample(5)

    Employee ID                Name   Salary   Age   Gender  Joining Date
15       8001.0       Martha Taylor  27238.0  56.0   Female    2014-07-28
61       2713.0       Ann Alexander  30123.0  34.0   Female    2020-10-13
13       3754.0         Laura Scott  21789.0   NaN   Female    2019-05-08
37       4756.0        Marilyn Cook  45217.0  44.0   Female    2012-04-13
59       8476.0   Christina Russell  45012.0  38.0   Female    2013-01-10

In [ ]:
df.sample(frac=0.3)  #show 30% of the data

#### Getting summary using `describe()`
You can also get the summary data for the data, using the function `describe()`.

In [18]:
# summary statistics for non-numeric columns is available by default only when all columns are non-numeric

display(df.describe())

       Employee ID        Salary        Age                   Joining Date
count    71.000000     71.000000  71.000000                             74
mean   5480.535211  40070.028169  41.845070  2016-04-29 06:09:43.783783680
min    1638.000000  19382.000000  26.000000            2010-06-21 00:00:00
25%    3581.500000  35073.000000  35.000000            2013-08-13 00:00:00
50%    5374.000000  40023.000000  41.000000            2016-08-24 12:00:00
75%    7404.500000  46166.500000  49.000000            2019-02-12 18:00:00
max    9731.000000  60234.000000  58.000000            2021-12-09 00:00:00
std    2349.482234   8036.594439   8.661323                            NaN

Lets look at another data file, this time we read from an excel file. containing both numerical and non-numerical (categorical)  data.

### Create DF from XLSX

Data: Basic-2.xlsx  
col_names: Column are simply labeled from `c1...c17`. There are 17 columns, defined respectively as:
1. dur: duration of agreement
2.  wage1.wage : wage increase in first year of contract
3.   wage2.wage : wage increase in second year of contract
4.   wage3.wage : wage increase in third year of contract
5.   cola : cost of living allowance
6.   hours.hrs : number of working hours during week
7.   pension : employer contributions to pension plan
8.   stby_pay : standby pay
9.   shift_diff : shift differencial : supplement for work on II and III shift
10.   educ_allw.boolean : education allowance
11.   holidays : number of statutory holidays
12.   vacation : number of paid vacation days
13.   lngtrm_disabil.boolean : employer's help during employee longterm disability
14.   dntl_ins : employers contribution towards the dental plan
15.   bereavement.boolean : employer's financial contribution towards the covering the costs of bereavement
16.   empl_hplan : employer's contribution towards the health plan
17.   empl_hplan : employer's contribution towards the health plan

Lets read and then display the data.

In [ ]:
# 1. Display the above data.
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Applied Programming/Basic-2.xlsx')

display(df)
#display(df.head())

What about the summary.

In [ ]:
df.describe()

Why do you think the count is different for each column?

Additionally, there were 17 columns, now there are only 8, what happened to the rest?

Count is different for each column, since count only counts non-`NaN` values. `NaN` or "**N**ot **a** **N**umber" refers to a value that is not representable as a number in a numeric column.  

So for example, c3 has 9 values that are `NaN` values.

As for the missing columns, `describe()` function by default summarizes only columns with numerical data if the data set contains both numerical and non-numerical (categorical) data.

There is a keyword argument `include` within describe that can be used to force describe to publish statistics for `all` columns,

In [20]:
# df.describe(include='all')

# It is used to show summary statistics of all columns of a dataframe, including non-numerical columns.
df.describe(include='all')

,Employee ID,Name,Salary,Age,Gender,Joining Date
count,71.000000,70,71.000000,71.000000,70,74
unique,NaN,70,NaN,NaN,2,NaN
top,NaN,Henry Alexander,NaN,NaN,Male,NaN
freq,NaN,1,NaN,NaN,35,NaN
mean,5480.535211,NaN,40070.028169,41.845070,NaN,2016-04-29 06:09:43.783783680
min,1638.000000,NaN,19382.000000,26.000000,NaN,2010-06-21 00:00:00
25%,3581.500000,NaN,35073.000000,35.000000,NaN,2013-08-13 00:00:00
50%,5374.000000,NaN,40023.000000,41.000000,NaN,2016-08-24 12:00:00
75%,7404.500000,NaN,46166.500000,49.000000,NaN,2019-02-12 18:00:00
max,9731.000000,NaN,60234.000000,58.000000,NaN,2021-12-09 00:00:00
std,2349.482234,NaN,8036.594439,8.661323,NaN,NaN

In [ ]:
df.describe(include='all')

However, doesn't work efficiently for categorical data.

Another option is to call `describe()` for categorical data separately.

In [21]:
# Show summary of non-numeric (object) columns
df.describe(include='object')

df.describe(exclude='float64')

                    Name  Gender                   Joining Date
count                 70      70                             74
unique                70       2                            NaN
top      Henry Alexander    Male                            NaN
freq                   1      35                            NaN
mean                 NaN     NaN  2016-04-29 06:09:43.783783680
min                  NaN     NaN            2010-06-21 00:00:00
25%                  NaN     NaN            2013-08-13 00:00:00
50%                  NaN     NaN            2016-08-24 12:00:00
75%                  NaN     NaN            2019-02-12 18:00:00
max                  NaN     NaN            2021-12-09 00:00:00

#### Getting information using `info()`
`pandas` also offers a method to get *information* about the dataframe, specifically, how many non-null elements in each column and what is the data type of each column.

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee ID    71 non-null     float64
 1    Name          70 non-null     object
 2    Salary        71 non-null     float64
 3    Age           71 non-null     float64
 4    Gender        70 non-null     object
 5    Joining Date  74 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 3.6+ KB

### Create DF from JSON

Data: iris.json  
col_names: Column are simply labeled from `c1...c17`. There are 17 columns, defined respectively as:
sepalLength: length of the sepal in centimeters.
sepalWidth: width of the sepal in centimeters.
petalLength: length of the petal in centimeters.
petalWidth: width of the petal in centimeters.
species: species of the Iris flower (Iris setosa, Iris virginica and Iris versicolor).

Lets read and then display the data.

In [23]:
df = pd.read_json('/content/drive/MyDrive/Applied Programming/iris.json')

display(df)
display(df.describe(include='object'))
display(df.describe())

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

       species
count      150
unique       3
top     setosa
freq        50

       sepalLength  sepalWidth  petalLength  petalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.057333     3.758000    1.199333
std       0.828066    0.435866     1.765298    0.762238
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

## Accessing Elements
`pandas` provide two different methods to access individual elements of a data frame.
- iloc() uses the default indices/positions (starting from 0) to access the particular element (similar to nD arrays).
- loc() uses the index row (if assigned) and column header to access the particular element.

Reading the first dataset again.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Applied Programming/Basic-1.csv', delimiter=',')

df

### Accessing via .iloc

Consider the dataset given in Basic-1.csv. Display second row, second column element.

# **Pandas DataFrame.loc[] Method**

Pandas DataFrame is a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). Arithmetic operations align on both row and column labels. It can be thought of as a dict-like container for Series objects. This is the primary data structure of the Pandas.

Pandas DataFrame loc[] Syntax
Pandas DataFrame.loc attribute accesses a group of rows and columns by label(s) or a boolean array in the given Pandas DataFrame.

In [25]:
print(df.iloc[1, 1])  #simple indexing

3.0

### Accessing via .loc

Consider the dataset given in Basic-1.csv. Display second row, second column element.

In [29]:
print(df.loc[0, 'sepalLength']) # 'sepalLength' is a valid column name   #here we are using given index (for row, both are same, since we never gave row any index).

5.1

## Slicing

Similar to previous list-like data types, you can access sequence of elements from within a dataframe. It does not need to be adjacent (or in sequence), i.e. you can pick few of the columns/rows in any order.

### Single Column Slice

Accessing a single column is simple. There are two formats,
1. Using a dot format, i.e. `df.COL_NAME`
2. Using the square bracket format, i.e. `df[COL_NAME]`

Consider the dataset given in Basic-2.xlsx. Display first column.

In [30]:
df = pd.read_excel('/content/drive/MyDrive/Applied Programming/Basic-2.xlsx')

df['c1']  #['c1'])

0     1.0
1     2.0
2     NaN
3     3.0
4     3.0
5     2.0
6     3.0
7     3.0
8     2.0
9     1.0
10    3.0
11    2.0
12    2.0
13    3.0
14    1.0
15    2.0
16    1.0
17    1.0
18    1.0
19    2.0
20    2.0
21    2.0
22    3.0
23    2.0
24    1.0
25    3.0
26    2.0
27    2.0
28    2.0
29    3.0
30    3.0
31    3.0
32    2.0
33    2.0
34    3.0
35    2.0
36    1.0
37    1.0
38    3.0
39    2.0
Name: c1, dtype: float64

Using the second format, i.e. square brackets, you can access multiple columns as long as you provide list of their labels in a comma separated list.

In [ ]:
df[['c1', 'c5']]

However, in order to access some rows over single/multiple columns, we can use `loc()` and `iloc()` functions as before. The indices will indicate that we are attempting to access multiple rows and/or columns.

### Slicing via .loc

Access and display first 10 rows from the second, third, fourth and fifth column.

In [ ]:
display(df.loc[0:9, 'c2':'c5'])

Access and display first second, fifth and eighth  row from the second and fifth column.

In [ ]:
display(df.loc[[0, 1, 4, 7], ['c2', 'c5']])  #not adjacent

### Slicing via .iloc

Same can be done using `iloc` (using positions instead of labels).

In [ ]:
display(df.iloc[0:9, 1:5])  #using position/rank of columns

In [ ]:
#Access and display first second, fifth and eighth  row from the second and fifth column.
display(df.iloc[[0, 1, 4, 7], 1:4])  #not adjacent or in  sequence

### Attributes of DataFrame
`pandas` library also provides multiple attributes for the dataframe. Some of the interesting ones are:
- `columns` : returns the list of labels of the columns of the dataframe.
- `index` : returns the index (labels)  of the columns of the dataframe.
- `shape` : returns the dimensions of the dataframe as a tuple.
- `dtypes` : returns the data type of each column.
- `values` : returns the data as a numpy array.
- `ndim` : returns the number of dimensions (axes).
- `size`: returns the total number of elements in the dataframe.
- `empty`: indicates whether the dataframe is empty or full.

Other functionality that is not an attribute but is used often:
- `count()`: returns the number non-zero elements in each column.
- value_counts(): returns a `Series` containing counts of unique values.

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Applied Programming/Basic-2.xlsx')

display(df)

In [ ]:
print('Dataframe has following columns.\n', df.columns)

print('Dataframe has following rows.\n', df.index)

print('The shape of the dataframe is:', df.shape)

print('Following is the data type of each column:\n', df.dtypes)

In [ ]:
print(f'Dataframe has {df.ndim} dimensions.')

print('Size of dataframe is: ', df.size)

print('Data Frame is empty', df.empty)

print('Following is the numpy array representation of the dataframe:\n',
      df.values)

In [ ]:
print(f'The number of non-null rows for each column are:\n{df.count()}'
      )  #count ignores nan-values

In [ ]:
df.value_counts() #unique values in each column

In [ ]:
df['c13'].value_counts() #for specific column, how many times each unique value showed up.

In [ ]:
df['c13'].value_counts()[
    'yes']  #for specific column, how many times 'yes; showed up.

## DF Selecting

Selecting is similar to the slicing. However, instead of accessing data by providing label/index (or positions) of the columns and rows, we are interested in accessing rows for which certain condition is true. These conditions may be regarding a single or multiple columns.

For example,

Consider the dataset given in Basic-1.csv.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Applied Programming/Basic-1.csv', delimiter=',')

display(df)

Lets say I want to get all the rows where `Job Type` is `White-collar`.

In [ ]:
selected_rows = df['Job Type'] == 'White-collar'

display(df.loc[selected_rows, :])

Lets go further,

    Display all rows related to White-collar jobs in Eastern Province.

In [ ]:
selected_rows = (df['Province'] == 'Eastern') & (df['Job Type']
                                                 == 'White-collar')

display(df.loc[selected_rows, :])

Look at the descriptive summary of the selected rows only.

In [ ]:
display(df.loc[selected_rows, :].describe())

#looking at only first column
display((df.loc[selected_rows, :].describe()
         )['Gender'])  #showing only first column's summary

Lets look at one more example, we follow the following steps:

Using the same dataset (Basic-1.csv).
1. Display all rows related to White-collar and Blue-collar jobs.
2. Display all rows related to White-collar and Blue-collar jobs for Females.
3. Display the statistical summary of Province column in the above selection.
4. Among all the White-collar and Blue-collar job Females, what proportion works in Eastern Province.

In [ ]:
#1. Display all rows related to White-collar and Blue-collar jobs.

#selected_rows = (df['Job Type']=='White-collar') | (df['Job Type']=='Blue-collar')

selected_rows = df['Job Type'].isin(['White-collar', 'Blue-collar'])

display(df.loc[selected_rows, :])

#display(df.loc[selected_rows,:].describe())

In [ ]:
# 2. Display all rows related to White-collar and Blue-collar jobs for Females.

selected_rows = df['Job Type'].isin(['White-collar', 'Blue-collar'
                                     ]) & (df['Gender'] == 'F')
display(df.loc[selected_rows, :])

In [ ]:
# 3. Display the statistical summary of Province column in the above selection.
df.loc[selected_rows, 'Province'].describe()

#df.loc[selected_rows,:].describe().loc[:,'Province']

In [ ]:
# 4. Among all the White-collar and Blue-collar job Females, what proportion works in Eastern Province.
#selected_rows is all rows corresponding to White-collar & Blue-collar Females (from previous cell)

ndf = df.loc[selected_rows, 'Province']

#ndf is now the last column (Province) of selected_rows

#value_counts['Eastern'] gives frequency of the value 'Eastern'
#index here provides list of indices of rows
print(ndf.index)

#proportion = ndf.value_counts()[2]/len(ndf.index)*100
proportion = ndf.value_counts()['Eastern'] / len(ndf.index) * 100

print(
    f'The proportion of Females working as blue/white collar in Eastern province is: {proportion: 0.2f}%'
)

## DF Sorting

You can sort dataframes using multiple columns.
The method is:

    sort_values(by,axis=0,inplace=False)

- `by` refers to which column/row you want to sort the dataframe. Can be an ordered list of columns/rows.
- `axis` is to choose whether to sort rows (0) or columns (1), default is 0 (rows)
- `inplace` refers to whether the original dataframe is to altered (True) or just return sorted copy (False).

There are some other parameters which we are skipping for this course.

Consider the dataset given in Basic-2.xlsx.

In [ ]:
import pandas as pd

#Read data
df = pd.read_excel('/content/drive/MyDrive/Applied Programming/Basic-2.xlsx')
display(df.head())

Sort the rows according to the first column, in ascending order. Repeat the sort in descending order.

 Inplace is an argument used in different functions. Some functions in which inplace is used as an attributes like, set_index(), dropna(), fillna(), reset_index(), drop(), replace() and many more. The default value of this attribute is False and it returns the copy of the object.

In [ ]:
# sort by single column in ascending order
df.sort_values(by=['c1'], inplace=True)
display(df.head())

# sort by single column in descending order
df.sort_values(by=['c1'], inplace=True, ascending=False)
display(df.head())

In [ ]:
#what happens if the column contains nan-values
display(df)

Consider the dataset given in Basic-2.xlsx. Sort the rows according to the first and then sixth column, where ascending in the first and descending in the sixth column. Display only first 6 columns.

In [ ]:
# sort by multiple columns
df.sort_values(by=['c1', 'c6'], inplace=True, ascending=[True, False])

display(df.iloc[:, 0:6])

display(df.info())
#display(df.loc[:,'c1':'c6'])

#### Sorting using row index

You can also sort columns with respect to row index.

In [ ]:
display(df.head())

df.sort_values(by=[0, 5], axis=1, inplace=True, ascending=[True, False])

display(df.head())

### Apply Functions

Functions can be applied to each row or column using *.apply()* method.

In [ ]:
# 1. In columns c1, c6 and c11, convert every number to the nearest integer.
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Applied Programming/Basic-2-Clean.csv')
display(df.head())
print(df.info())

Consider the data in file Basic-2-Clean.csv.
1. In columns c1, c6 and c11, convert every number to the nearest integer.
2. In column c12, replace the space between two words by underscore.

In [ ]:
df['c1'] = df['c1'].apply(lambda x: int(round(x)))  # apply for single column
df.loc[:, ['c6', 'c11']] = df.loc[:, ['c6', 'c11']].applymap(
    lambda x: int(round(x)))  #for multiple columns

display(df.head())
print(df.info())

In [ ]:
# 2. In column c12, replace the space between two words by underscore.
display(df.head())
df['c12'] = df['c12'].apply(lambda x: x.replace(' ', '_'))
display(df.head())

Similar to Lambda functions, user defined or built-in functions can be applied to each row or column using *.apply()* method. Moreover, *.applymap()* method can be used for multiple columns.

Consider the data in file Basic-2-Clean.csv.  
In columns c2, c3 and c9, round the values to the nearest 0, 0.5 or 1. If any value is negative, then replace it with zero.

In [ ]:
def custom_round(x):
    if x <= 0:
        return 0
    int_x = int(x)
    if (x <= int_x + 0.25):
        return int_x
    elif (x > int_x + 0.25) and (x <= int_x + 0.75):
        return int_x + 0.5
    else:
        return int_x + 1


import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Applied Programming/Basic-2-Clean.csv')
display(df.head())

In [ ]:
# df['c2']=df['c2'].apply(custom_round)  # for single column
df.loc[:, ['c2', 'c3', 'c9']] = df.loc[:, ['c2', 'c3', 'c9']].applymap(
    custom_round)  # for multiple columns
display(df.head())

# References:


## Data Sets:
1. Basic-2: Labor Relations Data, UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science. Published in: Bergadano, F., Matwin, S., Michalski, R., Zhang, J., Measuring Quality of Concept Descriptions, Procs. of the 3rd European Working Sessions on Learning, Glasgow, October 1988.


## Others:
1. Series: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html 📃
2. DataFrames: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html 📃
3. Read CSV: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html 📃
4. Read XLSX: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html 📃